name: CV Generator
on:
    workflow_run:
        workflows: ['pages-build-deployment']
        types: [completed]
jobs:
  Generate-CV:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: pull last code
        run: |
          git pull origin master

      - run: echo "Use Python to Convert the Markdown website to Latex"

      - run: echo "Use PDFLatex to generate the PDF"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Upload the PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dario-cv
          path: latex/CV_eng.pdf

      - name: update the CV branch
        run: |
          git clone -b cv git@github.com:dariopasquali/dariopasquali.github.io.git
          yes | cp -rf latex/* dariopasquali.github.io/
          cd dariopasquali.github.io
          git add --all
          git commit -m "update the CV"
          git push
          cd ..
          rm -Rf dariopasquali.github.io