name: CV Generator
on:
    workflow_run:
        workflows: ['pages-build-deployment']
        types: [completed]
jobs:
  Generate-CV:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use Python to Convert the Markdown website to Latex"
      - run: echo "Use PDFLatex to generate the PDF"
      - name: Upload the PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dario-cv
          path: generated/CV_eng.pdf